"use client";

import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Loader2, FileText, Sparkles, Download } from "lucide-react";
import { MarkdownRenderer } from "./markdown-renderer";
import type { PaperSection } from "@/lib/types";

function exportLatex(sections: PaperSection[]) {
  const content = sections.map((s) => s.content).join("\n\n");

  // Basic markdown → LaTeX conversion
  const latex = `\\documentclass[12pt,a4paper]{article}
\\usepackage[utf8]{inputenc}
\\usepackage{amsmath,amssymb}
\\usepackage{amsthm}
\\usepackage{hyperref}
\\usepackage{geometry}
\\geometry{margin=1in}

\\title{PaperForge --- Model Setup}
\\author{Generated by PaperForge}
\\date{\\today}

\\begin{document}
\\maketitle

${content
  .replace(/### /g, "\\subsection{")
  .replace(/## /g, "\\section{")
  .replace(/(?<=section\{[^}]+)\n/g, "}\n")
  .replace(/\*\*(.*?)\*\*/g, "\\textbf{$1}")
  .replace(/\*(.*?)\*/g, "\\textit{$1}")
  .replace(/\$\$([\s\S]*?)\$\$/g, "\\[$1\\]")
  .replace(/\$(.*?)\$/g, "\\($1\\)")
}

\\end{document}
`;

  const blob = new Blob([latex], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "paperforge-model-setup.tex";
  a.click();
  URL.revokeObjectURL(url);
}

interface OutputPanelProps {
  sections: PaperSection[];
  isGenerating: boolean;
  onGenerate: () => void;
}

export function OutputPanel({ sections, isGenerating, onGenerate }: OutputPanelProps) {
  return (
    <div className="space-y-4 animate-fade-in">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <FileText className="h-4 w-4 text-primary" />
          <h2 className="text-sm font-medium">生成内容</h2>
        </div>
        <div className="flex items-center gap-2">
          {sections.length > 0 && (
            <Button variant="outline" size="sm" className="h-8 gap-1.5" onClick={() => exportLatex(sections)}>
              <Download className="h-3.5 w-3.5" />
              导出 LaTeX
            </Button>
          )}
          <Button
            onClick={onGenerate}
            disabled={isGenerating || sections.length > 0}
            size="sm"
            className="h-8 gap-1.5"
          >
            {isGenerating ? (
              <>
                <Loader2 className="h-3.5 w-3.5 animate-spin" />
                生成中...
              </>
            ) : sections.length > 0 ? (
              "已生成"
            ) : (
              <>
                <Sparkles className="h-3.5 w-3.5" />
                生成 Model Setup
              </>
            )}
          </Button>
        </div>
      </div>

      <Card className="ring-1 ring-border overflow-hidden">
        <div className="h-0.5 bg-gradient-to-r from-primary/40 via-primary to-primary/40" />
        <CardContent className="p-6">
          {sections.length === 0 && !isGenerating && (
            <div className="text-center py-12">
              <FileText className="h-8 w-8 text-muted-foreground/30 mx-auto mb-3" />
              <p className="text-sm text-muted-foreground">
                完成模型定义后，点击上方按钮生成论文章节
              </p>
            </div>
          )}
          {isGenerating && sections.length === 0 && (
            <div className="flex items-center justify-center py-12">
              <div className="flex items-center gap-3">
                <Loader2 className="h-5 w-5 animate-spin text-primary" />
                <div>
                  <p className="text-sm font-medium">AI 正在生成内容...</p>
                  <p className="text-xs text-muted-foreground mt-0.5">这可能需要 30 秒左右</p>
                </div>
              </div>
            </div>
          )}
          {sections.map((section, i) => (
            <div key={section.id} className="prose-academic animate-fade-in" style={{ animationDelay: `${i * 100}ms` }}>
              {i > 0 && <hr className="my-6 border-border" />}
              <MarkdownRenderer content={section.content} />
            </div>
          ))}
        </CardContent>
      </Card>
    </div>
  );
}
